version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

    environment:
      TEST_ARTIFACTS: /tmp/artifacts

    steps:
      - checkout
      - run: mkdir -p $TEST_ARTIFACTS            
      - run: make dep
      - run: 
          command: |
            make coverhtml
            mv coverage.html $TEST_ARTIFACTS
    
      - store_artifacts:
          path: $TEST_ARTIFACTS